(() => {
  const A='/';
  const money=n=>Number(n||0).toLocaleString('ar-IQ')+' د.ع';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const store={cart:JSON.parse(localStorage.getItem('wasselni_cart')||'[]'),orders:JSON.parse(localStorage.getItem('wasselni_orders')||'[]'),fav:JSON.parse(localStorage.getItem('wasselni_fav')||'[]')};
  const save=()=>{localStorage.setItem('wasselni_cart',JSON.stringify(store.cart));localStorage.setItem('wasselni_orders',JSON.stringify(store.orders));localStorage.setItem('wasselni_fav',JSON.stringify(store.fav));};
  const restaurants=[
    {id:'r1',name:'بيت بغداد',type:'عراقي',rating:4.9,time:'25–35',fee:1500,tag:'أكل عراقي بلمسة حديثة',img:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80',offer:'خصم 20%',items:[['تشريب لحم','14,000'],['كباب بغدادي','18,000'],['دولمة البيت','16,000'],['برياني دجاج','15,000']]},
    {id:'r2',name:'أول بايت برغر',type:'برغر',rating:4.8,time:'20–30',fee:1250,tag:'برغر سموكي وصوصات خاصة',img:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80',offer:'توصيل مخفض',items:[['سموكي دبل','14,000'],['ترافل برغر','17,000'],['تشكن كرسبي','12,000'],['فرايز تشيز','7,000']]},
    {id:'r3',name:'فرن المدينة',type:'بيتزا',rating:4.7,time:'25–40',fee:1750,tag:'بيتزا طازجة من الفرن',img:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=80',offer:'وجبة شخصين',items:[['مارغريتا','12,000'],['بيبروني','15,000'],['دجاج باربكيو','16,000'],['أربع أجبان','17,000']]},
    {id:'r4',name:'مشاوي الدار',type:'مشويات',rating:4.9,time:'30–45',fee:2000,tag:'كباب وتكة على الفحم',img:'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80',offer:'مشروب مجاني',items:[['كباب لحم','18,000'],['تكة دجاج','17,000'],['مشاوي مشكلة','29,000'],['صحن مقبلات','8,000']]},
    {id:'r5',name:'صباح الخير',type:'فطور',rating:4.8,time:'15–25',fee:1000,tag:'فطور عراقي وشرقي',img:'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=900&q=80',offer:'قهوة علينا',items:[['فطور عراقي','12,000'],['شكشوكة','9,000'],['بيض وقيمر','10,000'],['صحن جبن','7,000']]},
    {id:'r6',name:'مزاج كافيه',type:'قهوة',rating:4.7,time:'15–25',fee:750,tag:'قهوة مختصة ومشروبات باردة',img:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80',offer:'خصم 15%',items:[['لاتيه','6,000'],['سبانش لاتيه','7,000'],['آيس كوفي','7,000'],['كوكيز','4,000']]}
  ];
  const cats=['الكل','برغر','دجاج','بيتزا','عراقي','مشويات','فطور','حلويات','قهوة'];
  const q=new URLSearchParams(location.search);
  const page=document.body.dataset.page||'home';
  const find=id=>restaurants.find(x=>x.id===id)||restaurants[0];
  function nav(active){return `<header class="top"><a class="brand" href="./index.html"><span>و</span><b>وصّلني</b></a><div class="address"><small>التوصيل إلى</small><strong>بغداد، العراق⌄</strong></div><nav><a class="${active==='home'?'on':''}" href="./index.html">الرئيسية</a><a class="${active==='restaurants'?'on':''}" href="./restaurants.html">اكتشف</a><a class="${active==='orders'?'on':''}" href="./orders.html">طلباتي</a><a class="${active==='account'?'on':''}" href="./account.html">حسابي</a></nav><a class="cart" href="./cart.html">السلة <i>${store.cart.length}</i></a></header>`}
  const footer=`<footer><div><span class="brand-mini">و</span><b>وصّلني</b><p>منصة توصيل عراقية مصممة حتى تخلي الطلب أسهل، أوضح، وأسرع.</p></div><div><b>اكتشف</b><a href="./restaurants.html">المطاعم</a><a href="./orders.html">تتبع الطلب</a><a href="./account.html">حسابي</a></div><div><b>مساعدة</b><a href="./account.html">مركز الدعم</a><a href="./account.html">سياسة الخصوصية</a><a href="./account.html">شروط الاستخدام</a></div></footer>`;
  const card=r=>`<article class="r-card"><a class="r-photo" href="./restaurant.html?id=${r.id}" style="background-image:url('${r.img}')"><span class="offer">${esc(r.offer)}</span><button class="heart" data-fav="${r.id}" type="button">${store.fav.includes(r.id)?'♥':'♡'}</button></a><div class="r-body"><div class="r-title"><div><h3>${esc(r.name)}</h3><span>${esc(r.type)} · ${esc(r.tag)}</span></div><b>★ ${r.rating}</b></div><div class="r-meta"><span>⌛ ${r.time} دقيقة</span><span>🛵 ${money(r.fee)}</span><span class="open">مفتوح</span></div></div></article>`;
  function bind(){document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const id=b.dataset.fav;store.fav=store.fav.includes(id)?store.fav.filter(x=>x!==id):[...store.fav,id];save();b.textContent=store.fav.includes(id)?'♥':'♡'});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const [rid,idx]=b.dataset.add.split('|');const r=find(rid),it=r.items[idx];store.cart.push({rid,name:it[0],price:Number(it[1].replace(/,/g,'')),qty:1});save();toast('انضاف للسلة');document.querySelectorAll('.cart i').forEach(x=>x.textContent=store.cart.length)})}
  function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),1800)}
  function home(){document.querySelector('#app').innerHTML=nav('home')+`<main><section class="hero"><div class="hero-copy"><span class="eyebrow">🇮🇶 مصمم للعراق من البداية</span><h1>مو بس نوصل طلبك.<br><em>نوصلّك للشي اللي تريده.</em></h1><p>مطاعم مختارة، عروض حقيقية، وتتبع واضح للطلب من لحظة ما تضغط «اطلب» لحد ما يوصل لبابك.</p><div class="search"><span>⌕</span><input id="search" placeholder="شنو نفسك اليوم؟ برغر، كباب، قهوة..."><button onclick="location.href='./restaurants.html?q='+encodeURIComponent(document.querySelector('#search').value)">ابحث</button></div><div class="proof"><span>✓ أسعار واضحة</span><span>✓ تتبع الطلب</span><span>✓ دعم حقيقي</span></div></div><div class="hero-card"><div class="hero-card-top"><span>طلبك الآن</span><b>قيد التوصيل</b></div><div class="hero-food" style="background-image:url('${restaurants[1].img}')"></div><h3>أول بايت برغر</h3><p>سموكي دبل × 1 · فرايز تشيز × 1</p><div class="progress"><i></i></div><div class="eta"><span>السائق بالطريق</span><b>12 دقيقة</b></div></div></section><section class="trust"><div><b>اختيارات مرتبة</b><span>مو فوضى مطاعم</span></div><div><b>سعر التوصيل واضح</b><span>قبل ما تأكد الطلب</span></div><div><b>كل خطوة واضحة</b><span>بدون تخمين</span></div><div><b>دعم عند الحاجة</b><span>مو روبوت وبس</span></div></section><section class="section"><div class="head"><div><small>اختار مزاجك</small><h2>شنو تريد اليوم؟</h2></div><a href="./restaurants.html">شوف الكل ←</a></div><div class="cat-row">${cats.slice(1).map((c,i)=>`<a href="./restaurants.html?cat=${encodeURIComponent(c)}"><span>${['🍔','🍗','🍕','🍲','🥩','🍳','🍰','☕'][i]}</span><b>${c}</b></a>`).join('')}</div></section><section class="section"><div class="head"><div><small>مختارات وصّلني</small><h2>مطاعم الناس تحب ترجع لها</h2></div><a href="./restaurants.html">عرض الكل ←</a></div><div class="grid">${restaurants.map(card).join('')}</div></section><section class="why"><div><small>ليش وصّلني؟</small><h2>نريد نخلي الطلب تجربة، مو مهمة.</h2></div><div class="why-grid"><article><b>01</b><h3>تشوف كلشي بوضوح</h3><p>السعر، التوصيل، الوقت، والخصم قبل التأكيد.</p></article><article><b>02</b><h3>تعرف طلبك وين</h3><p>حالات واضحة من قبول المطعم إلى وصول السائق.</p></article><article><b>03</b><h3>ترجع بسهولة</h3><p>طلباتك السابقة ومفضلاتك جاهزة للطلب من جديد.</p></article></div></section></main>${footer}`;bind()}
  function restaurantsPage(){const cat=q.get('cat')||'الكل', term=(q.get('q')||'').trim();let list=restaurants.filter(r=>(cat==='الكل'||r.type===cat)&&(!term||(r.name+r.type+r.tag).includes(term)));document.querySelector('#app').innerHTML=nav('restaurants')+`<main><section class="listing-head"><div><small>اكتشف</small><h1>اختياراتك اليوم</h1><p>مطاعم مرتبة بطريقة تخليك توصل للقرار بسرعة.</p></div><div class="filter"><input id="filter" value="${esc(term)}" placeholder="ابحث عن مطعم أو نوع أكل"><button onclick="location.href='./restaurants.html?q='+encodeURIComponent(document.querySelector('#filter').value)">بحث</button></div></section><div class="chips">${cats.map(c=>`<a class="${c===cat?'sel':''}" href="./restaurants.html?cat=${encodeURIComponent(c)}">${c}</a>`).join('')}</div><div class="grid">${list.length?list.map(card).join(''):`<div class="empty"><h3>ما لقينا هالاختيار بعد</h3><p>جرّب اسم أو تصنيف ثاني.</p></div>`}</div></main>${footer}`;bind()}
  function restaurantPage(){const r=find(q.get('id'));document.querySelector('#app').innerHTML=nav('restaurants')+`<main><section class="restaurant-cover" style="background-image:url('${r.img}')"><div><span>${r.type}</span><h1>${r.name}</h1><p>${r.tag}</p><b>★ ${r.rating} · ${r.time} دقيقة · ${money(r.fee)} توصيل</b></div></section><div class="restaurant-layout"><section><div class="menu-head"><div><small>منيو ${r.name}</small><h2>اختار اللي يعجبك</h2></div><span>الأسعار بالدينار العراقي</span></div><div class="menu-list">${r.items.map((it,i)=>`<article class="menu-item"><div class="menu-img" style="background-image:url('${r.img}')"></div><div><h3>${it[0]}</h3><p>${r.tag}</p><b>${money(Number(it[1].replace(/,/g,'')))}</b></div><button data-add="${r.id}|${i}">+ إضافة</button></article>`).join('')}</div></section><aside class="summary"><small>سلة الطلب</small><h3>${store.cart.length} أصناف</h3><p>تقدر تضيف أكثر من صنف وتراجع طلبك قبل التأكيد.</p><a class="primary" href="./cart.html">فتح السلة ←</a></aside></div></main>${footer}`;bind()}
  function cartPage(){const total=store.cart.reduce((s,x)=>s+x.price*x.qty,0),delivery=store.cart.length?1500:0;document.querySelector('#app').innerHTML=nav('')+`<main><section class="listing-head"><div><small>السلة</small><h1>طلبك مرتب.</h1><p>${store.cart.length?'راجع الأصناف قبل ما نروح للدفع.':'السلة فارغة حالياً.'}</p></div></section>${store.cart.length?`<div class="cart-layout"><section class="cart-list">${store.cart.map((x,i)=>`<article><div><h3>${esc(x.name)}</h3><span>${money(x.price)} × ${x.qty}</span></div><button onclick="removeItem(${i})">حذف</button></article>`).join('')}</section><aside class="checkout-box"><div><span>المجموع</span><b>${money(total)}</b></div><div><span>التوصيل</span><b>${money(delivery)}</b></div><hr><div><strong>الإجمالي</strong><strong>${money(total+delivery)}</strong></div><a class="primary" href="./checkout.html">متابعة للدفع</a></aside></div>`:`<div class="empty"><div class="empty-icon">🛍️</div><h2>السلة تنتظر طلبك</h2><a class="primary" href="./restaurants.html">اكتشف المطاعم</a></div>`}</main>${footer}`}
  window.removeItem=i=>{store.cart.splice(i,1);save();cartPage()};
  function checkout(){const total=store.cart.reduce((s,x)=>s+x.price*x.qty,0)+1500;document.querySelector('#app').innerHTML=nav('')+`<main><section class="listing-head"><div><small>آخر خطوة</small><h1>خل نوصله إلك.</h1><p>معلومات بسيطة حتى نبدأ الطلب.</p></div></section><div class="checkout-layout"><section class="form-card"><label>الاسم<input id="name" placeholder="اسمك"></label><label>رقم الهاتف<input id="phone" placeholder="07xxxxxxxxx" inputmode="tel"></label><label>العنوان<input id="address" placeholder="المنطقة، الشارع، أقرب نقطة دالة"></label><label>طريقة الدفع<select id="payment"><option>الدفع عند الاستلام</option><option>دفع إلكتروني — جاهز للربط</option></select></label><label>ملاحظة للطلب<textarea id="note" placeholder="مثلاً: بدون بصل"></textarea></label><button class="primary" onclick="placeOrder()">تأكيد الطلب · ${money(total)}</button></section><aside class="summary"><small>ملخص</small><h2>${money(total)}</h2><p>يشمل التوصيل التقديري. السعر النهائي يظهر قبل الإرسال في النسخة المرتبطة بالخدمة.</p></aside></div></main>${footer}`}
  window.placeOrder=()=>{if(!document.querySelector('#name').value||!document.querySelector('#phone').value||!document.querySelector('#address').value){toast('كمل الاسم والهاتف والعنوان');return}const order={id:'W'+Date.now().toString().slice(-7),createdAt:new Date().toISOString(),status:'جاري تأكيد المطعم',total:store.cart.reduce((s,x)=>s+x.price*x.qty,0)+1500,customer:document.querySelector('#name').value,address:document.querySelector('#address').value,items:[...store.cart]};store.orders.unshift(order);store.cart=[];save();location.href='./orders.html'};
  function orders(){document.querySelector('#app').innerHTML=nav('orders')+`<main><section class="listing-head"><div><small>المتابعة</small><h1>طلباتي</h1><p>كل طلب إله رحلة واضحة.</p></div></section>${store.orders.length?store.orders.map(o=>`<article class="order-card"><div class="order-top"><div><b>#${o.id}</b><span>${new Date(o.createdAt).toLocaleDateString('ar-IQ')}</span></div><strong>${money(o.total)}</strong></div><div class="timeline"><i class="done">✓<small>تم الطلب</small></i><i class="active">2<small>${esc(o.status)}</small></i><i>3<small>السائق بالطريق</small></i><i>4<small>تم التسليم</small></i></div><p>📍 ${esc(o.address)}</p></article>`).join(''):`<div class="empty"><div class="empty-icon">📦</div><h2>بعدك ما طلبت</h2><p>أول طلب راح يظهر هنا وتتبع حالته يصير من نفس الصفحة.</p><a class="primary" href="./restaurants.html">ابدأ أول طلب</a></div>`}</main>${footer}`}
  function account(){document.querySelector('#app').innerHTML=nav('account')+`<main><section class="profile"><div class="avatar">و</div><div><small>حسابك في وصّلني</small><h1>أهلاً بيك 👋</h1><p>إدارة بياناتك وعناوينك ومفضلاتك من مكان واحد.</p></div></section><div class="account-grid"><a href="./account.html#addresses"><b>📍 عناويني</b><span>أضف البيت، العمل، أو أي عنوان</span></a><a href="./restaurants.html?fav=1"><b>♥ المفضلة</b><span>${store.fav.length} مطاعم محفوظة</span></a><a href="./orders.html"><b>📦 طلباتي</b><span>${store.orders.length} طلب</span></a><a href="./restaurants.html"><b>🎟️ كوبوناتي</b><span>العروض المتاحة تظهر هنا</span></a></div></main>${footer}`}
  if(page==='home')home();else if(page==='restaurants')restaurantsPage();else if(page==='restaurant')restaurantPage();else if(page==='cart')cartPage();else if(page==='checkout')checkout();else if(page==='orders')orders();else account();
})();
