-- WASSELNI V2 — independent delivery platform database
-- Run this in the WASSELNI Supabase project only.
-- This schema is intentionally separate from KIWI/Firebase.

create extension if not exists pgcrypto;

create table if not exists public.restaurants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text,
  address text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.drivers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text,
  pin_hash text,
  active boolean not null default true,
  available boolean not null default false,
  vehicle_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text,
  phone text,
  default_address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Main independent delivery order table.
create table if not exists public.orders (
  id text primary key,
  order_code text unique,
  source_system text not null default 'wasselni',
  source_order_id text,
  restaurant_id uuid references public.restaurants(id) on delete set null,
  restaurant_name text,
  customer_id uuid references public.customers(id) on delete set null,
  customer_name text not null default '',
  phone text,
  address text,
  landmark text,
  payment_method text,
  items jsonb not null default '[]'::jsonb,
  total numeric not null default 0,
  delivery_fee numeric not null default 0,
  driver_fee numeric not null default 0,
  note text,
  status text not null default 'pending',
  restaurant_status text not null default 'pending',
  driver_status text not null default 'waiting',
  driver_id uuid references public.drivers(id) on delete set null,
  driver_name text,
  invoice_number text,
  invoice_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  driver_accepted_at timestamptz,
  picked_up_at timestamptz,
  delivered_at timestamptz
);

create unique index if not exists orders_source_unique
  on public.orders(source_system, source_order_id)
  where source_order_id is not null;

create index if not exists orders_status_idx on public.orders(status, created_at desc);
create index if not exists orders_driver_idx on public.orders(driver_id, status, created_at desc);
create index if not exists orders_restaurant_idx on public.orders(restaurant_id, status, created_at desc);

create table if not exists public.order_events (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  event_type text not null,
  old_status text,
  new_status text,
  actor_type text not null default 'system',
  actor_id text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists order_events_order_idx
  on public.order_events(order_id, created_at desc);

create table if not exists public.integration_instances (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid references public.restaurants(id) on delete cascade,
  provider text not null,
  name text not null,
  active boolean not null default true,
  config jsonb not null default '{}'::jsonb,
  last_sync_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists integration_provider_idx
  on public.integration_instances(provider, active);

-- Backward-compatible columns used by the current Wasselni pages.
alter table public.orders add column if not exists customer text;
alter table public.orders add column if not exists phone text;
alter table public.orders add column if not exists address text;
alter table public.orders add column if not exists payment text;
alter table public.orders add column if not exists note text;
alter table public.orders add column if not exists driver_id_text text;

-- Keep the current static frontend working during development.
-- IMPORTANT: replace these public policies with authenticated role policies before commercial launch.
alter table public.restaurants enable row level security;
alter table public.drivers enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_events enable row level security;
alter table public.integration_instances enable row level security;

drop policy if exists "wasselni public restaurants read" on public.restaurants;
create policy "wasselni public restaurants read" on public.restaurants for select to anon using (active = true);

drop policy if exists "wasselni public drivers read" on public.drivers;
create policy "wasselni public drivers read" on public.drivers for select to anon using (active = true);

drop policy if exists "wasselni public orders read" on public.orders;
create policy "wasselni public orders read" on public.orders for select to anon using (true);

drop policy if exists "wasselni public orders insert" on public.orders;
create policy "wasselni public orders insert" on public.orders for insert to anon with check (true);

drop policy if exists "wasselni public orders update" on public.orders;
create policy "wasselni public orders update" on public.orders for update to anon using (true) with check (true);

drop policy if exists "wasselni public order events insert" on public.order_events;
create policy "wasselni public order events insert" on public.order_events for insert to anon with check (true);

grant usage on schema public to anon;
grant select on public.restaurants, public.drivers to anon;
grant select, insert, update on public.orders to anon;
grant insert on public.order_events to anon;

alter publication supabase_realtime add table public.orders;
alter publication supabase_realtime add table public.order_events;

-- A small compatibility trigger keeps the old customer/payment names in sync.
create or replace function public.wasselni_sync_legacy_fields()
returns trigger language plpgsql as $$
begin
  if new.customer is null or new.customer = '' then new.customer := new.customer_name; end if;
  if new.customer_name is null or new.customer_name = '' then new.customer_name := coalesce(new.customer, ''); end if;
  if new.payment is null or new.payment = '' then new.payment := new.payment_method; end if;
  if new.payment_method is null or new.payment_method = '' then new.payment_method := new.payment; end if;
  return new;
end;
$$;

drop trigger if exists wasselni_sync_legacy_fields on public.orders;
create trigger wasselni_sync_legacy_fields
before insert or update on public.orders
for each row execute function public.wasselni_sync_legacy_fields();
